version: '3.1'

services:

  php:
    container_name: php-tdd
    build: 
      context: .
      dockerfile: Dockerfile
    image: company/php-tdd
    cap_drop: [all]
    cap_add: [chown, setuid, setgid, setfcap]
    volumes:
      - ./:/tdd
    working_dir: /tdd

